import type { Metadata } from "next";
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
import { Geist, Geist_Mono } from "next/font/google";
import Footer from "@/components/utilisateur/Footer";
>>>>>>> 876a674 (footer)
import "./globals.css";
<<<<<<< HEAD
import Navbar from "@/components/utilisateur/Navbar";
=======
import MobileMenu from "@/components/utilisateur/MobileMenu"
>>>>>>> bebac7d (menu burger)
=======
import { Geist, Geist_Mono } from "next/font/google";
=======
>>>>>>> 11633f7 (	modified:   src/app/layout.tsx)
import Footer from "@/components/utilisateur/Footer";
import "./globals.css";
import Navbar from "@/components/utilisateur/Navbar";
>>>>>>> ed88f5f (Navebaré)

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    <html lang="fr">
      <body >
        <Navbar />
        <main>
        {children}
        </main>
      </body>
=======
=======
>>>>>>> ed88f5f (Navebaré)
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
<<<<<<< HEAD

      >
=======
      > <MobileMenu />
>>>>>>> eb0499e (menu burger)
        {children}
        <Footer />
        </body>
<<<<<<< HEAD
>>>>>>> 876a674 (footer)
=======
=======
=======
>>>>>>> 11633f7 (	modified:   src/app/layout.tsx)
    <html lang="fr">
      <body>
        <Navbar />
        <main>
          {children}
        </main>
        <Footer />
      </body>
<<<<<<< HEAD
>>>>>>> fcbb749 (Navebaré)
>>>>>>> ed88f5f (Navebaré)
=======
>>>>>>> 11633f7 (	modified:   src/app/layout.tsx)
    </html>
  );
}