<<<<<<< HEAD
import type { Metadata } from "next";
import Footer from "@/components/utilisateur/Footer";
=======
>>>>>>> df72e3483948bf00876cfc5ceb65dea24585e8f0
import "./globals.css";
import StatsSection from "@/components/sections/StatsSection";
import Navbar from "@/components/utilisateur/Navbar";
import Footer from "@/components/utilisateur/Footer";



<<<<<<< HEAD

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
=======
>>>>>>> df72e3483948bf00876cfc5ceb65dea24585e8f0

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html lang="fr">
      <body>
        <Navbar />
        {children}
        <StatsSection />
        <Footer />
        </body>
    </html>
=======
     <html lang="fr">
      <body>
        <Navbar />
        <main>
         {children}
        </main>
        <Footer />
      </body>
     </html>
>>>>>>> df72e3483948bf00876cfc5ceb65dea24585e8f0
  );
}