import type { Metadata } from "next";
import Footer from "@/components/utilisateur/Footer";
import "./globals.css";
import StatsSection from "@/components/sections/StatsSection";
import Navbar from "@/components/utilisateur/Navbar";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body>
        <Navbar />
        {children}
        <StatsSection />
        <Footer />
        </body>
    </html>
  );
}
